config/routes.rb
Rails.application.routes.draw do
  get 'setup/quicksetup'
  post 'setup/quicksetup'
  get 'setup/advanced'
  get 'wifi/status'
  post 'session/login'

  match 'login', to: 'session#login_panel', via: :get
  match 'logout', to: 'session#logout', via: :get
  get 'session/login_panel'
  get 'wifi/wifi_on'
  get 'wifi/wifi_off'
  root 'basic#status'
  resources :users

end

app/models/adapter.rb
class Adapter < ActiveRecord::Base
end

app/models/environment.rb
class Environment < ActiveRecord::Base
  require 'mac-address'
public
  def self.safeFirst #guaranteed to yield some results even if database was purged
    self.setIfEmpty
    self.first
  end

private
  def self.setIfEmpty
    if Environment.first.nil?
      env = Environment.new
      env.operating_system=RUBY_PLATFORM
      env.current_version="0.01" #temporary, will make it into something nice later
      env.adapter_count = MacAddress.address.list.count
      env.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  validates :level, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper
  attr_accessor :user
  before_action :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    if !isLoggedIn?
      redirect_to login_path and @loggedUser = nil and return
    else
      @loggedUser ||= showUser #this is pretty much a User.find using session[:user_id]
    end
  end

  def adminAuthorize
    flash[:error] = "You don't have necessary privileges to access this feature" and redirect_to root_path unless @loggedUser.level>=1 #admins have privileges level of 2
  end
end

app/controllers/basic_controller.rb
class BasicController < ApplicationController
  require 'wifi_client_handler'
  include BasicHelper
  #skip_before_action :authorize
  def status
    @specs = Environment.safeFirst
    @macs = getMacs
    begin
    @uptime = uptime
    rescue
      @uptimeError = true
    end
    @systemLoad = (systemLoad*100).to_i
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  include SessionHelper
  layout "login"
  skip_before_action :authorize
  def login
    invalidAttempt and render 'login_panel' and return unless session_params[:username] and
                session_params[:password] and User.exists?(:username => session_params[:username].to_s)
    user = User.find_by username: session_params[:username].to_s
    invalidAttempt and render 'login_panel' and return unless user.authenticate(session_params[:password])
    logIn(user)
    redirect_to root_path
  end

  def logout
    logOut
    flash.now[:info] = "You have successfully logged out"
    render 'login_panel'
  end

  def login_panel
    redirect_to root_path and flash[:info] = "You are already logged in" and return if isLoggedIn?
  end

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  require 'wifi_client_handler'
  include BasicHelper

  def quicksetup
    @specs = Environment.safeFirst
    render "setup/quicksetup/quicksetup"
  end

  def advanced
    @specs = Environment.safeFirst
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :adminAuthorize

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :level)
    end
end

app/controllers/wifi_controller.rb
class WifiController < ApplicationController
  include WifiHelper

  def status

  end

  def wifi_on
    if turn_on
      flash[:info]="WiFi has been enabled" and redirect_to wifi_status_path and return
    else
      flash[:info]="Something went wrong" and redirect_to wifi_status_path and return
    end
  end

  def wifi_off
    if turn_off
      flash[:info]="WiFi has been disabled" and redirect_to wifi_status_path and return
    else
      flash[:info]="Something went wrong" and redirect_to wifi_status_path and return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_helper.rb
module BasicHelper
  require 'mac-address'
  require 'sysinfo'
  require 'open3' #the module to have a sanitized input/output from system calls so we won't have HDD formatted or something similar by mistake
  require 'usagewatch'
  require 'sys/filesystem'
  def getMacs
    MacAddress.address.list
  end

  def wifiAvailable?
    stdout = Open3.capture2("ifconfig | grep 'wlan'")
    return true if stdout[0].split("\n").length >= 1 #this actually gives the number of wlan adapters
    return false
  end

  def uptime
    begin
    uptime = uptimeHours
    formatted = Hash.new
    formatted[:hours] = uptime.to_i
    formatted[:minutes] = (uptime*60%60)
    formatted[:seconds] = ((uptime*3600%3600)%60).to_i
    formatted[:minutes] = formatted[:minutes].to_i
    return formatted
    rescue
    raise "Uptime cannot be determined"
    end
  end

  def cores
    core_count = Open3.capture2("nproc")
    core_count = core_count[0].to_i
    core_count
  end

  def systemLoad
    avg_load = Open3.capture2("uptime")
    index = avg_load[0].index('load average:')
    avg_load = avg_load[0].slice(index+14, 4)
    avg_load[","]="."
    return avg_load.to_f/cores #avg_load can easily exceed 1.00 and should be divided by core count if you want something that makes sense
  end
  private

  def uptimeHours
    sysinfo = SysInfo.new
    return sysinfo.uptime
  end

  def freeSpace
    stat = Sys::Filesystem.stat("/")
    mb_available = stat.block_size * stat.blocks_available / 1024 / 1024
    mb_available
  end
  def topProcesses
    usw = Usagewatch
    usw.uw_cputop
  end
end

app/helpers/session_helper.rb
module SessionHelper

  def isLoggedIn?
    session[:timestamp] = 15.minutes.from_now and return true if session[:user_id] and
                          session[:timestamp] and session[:timestamp].to_datetime > Time.now
    logOut and return false
  end

  def logIn(user)
    session[:user_id] = user.id
    session[:timestamp] = 15.minutes.from_now
  end

  def logOut
    reset_session
  end

  def showUser
    user = User.find(session[:user_id])
    return user
  end

  def invalidAttempt
    flash.now[:error] = "Your login/password is incorrect."
  end
end

app/helpers/setup_helper.rb
module SetupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wifi_helper.rb
module WifiHelper
  def turn_on
    path = Rails.root.to_s + "/scripts/"
    stdout, status = Open3.capture2("#{path}/wifi_start")
    return true if status == 0
    return false
  end

  def turn_off
    path = Rails.root.to_s + "/scripts/"
    stdout, status = Open3.capture2("#{path}/wifi_stop")
    return true if status == 0
    return false
  end
end

app/views/basic/status.html.erb
<div class = "container">
<% if flash[:error] %>
<div class = "alert alert-danger"><%= flash[:error] %></div>
<% end %>
<% if flash[:info] %>
<div class = "alert alert-info"><%= flash[:info] %></div>
<% end %>
<p>Current version: <%= @specs.current_version %></p>
<p>Operating system: <%= @specs.operating_system %>
<p>Network adapters: <%= @specs.adapter_count %></p>
<% @macs.each do |mac| %>
<p>MAC Address: <%= mac %> </p>
<% end %>
<% if wifiAvailable? %>
<p>WiFi available </p>
<% else %>
<p>WiFi unavailable</p>
<% end %>
Hello, <%= @loggedUser.username %><br />
System up time:
<% if @uptimeError %>
Uptime can't be determined yet, please wait<br />
<% else %>
<%= @uptime[:hours] %> hours, <%= @uptime[:minutes] %> minutes and <%= @uptime[:seconds] %> seconds <br />
<% end %>
Average CPU load: <%= @systemLoad %>% <br /> <% if @systemLoad>=100 %> Warning - CPU load exceeds 100%, delays may occur <br /><% end %>
Free space: <%= (freeSpace/1024.to_f).round(2) %>GB
<br />
Top ten processes:<br />
<ul>
<% topProcesses.each do |process| %>
<li><%= process[0] %> - <%= ((process[1].to_f)/cores.to_f).round(2) %> % CPU used </li>
<% end %>
</ul>
</div>
<div class = "help_bar">
Current version shows the version of the Debian-Router firmware
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Debian-router</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
  <div class = "main_bar">
    <div class = "menu_bar">
      <ul class="nav nav-pills nav-stacked" role="tablist">
        <li><%= link_to "Status", root_path %></li>
        <li><%= link_to "WiFi", wifi_status_path %></li>
        <li><a href="#">Lan</a></li>
        <li><%= link_to "Logout", logout_path %></li>
      </ul>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Debian-router</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = "login">
<%= yield %>
</div>
</body>
</html>

app/views/session/login_panel.html.erb
<% if flash[:error] %>
<div class = "alert alert-danger"><%= flash[:error] %></div>
<% end %>

<% if flash[:info] %>
<div class = "alert alert-info"><%= flash[:info] %></div>
<% end %>

<h1>Login panel</h1>
<%= form_for :session, url: session_login_path do |f| %>
<table class = "table table-bordered">
<tbody>
<tr><td>
Login</td><td><%= f.text_field :username %></td></tr>
<tr><td>Password</td><td>
<%= f.password_field :password %></td></tr>
<tr><td><%= f.submit "Login", :class => "btn btn-default btn-lg" %></td></tr>
</tbody>
</table>
<% end %>

app/views/setup/advanced.html.erb
<div class = "container">
<h1>Setup#advanced</h1>
<p>Find me in app/views/setup/advanced.html.erb</p>
</div>

app/views/setup/quicksetup/quicksetup.html.erb
<div class = "container">
<h1>Quick guide to walk you through setting up this device</h1>
<% if wifiAvailable? %>
<p>It seems Wifi is available for this machine meaning you have 2 options - you can either get internet through Wifi or through LAN.</p>
<%= form_for "quicksetup" do |f| %>
  Choose which adapter will you use to connect to internet:<br>
  <%= f.label :lan %>
  <%= f.radio_button(:adapter, "lan", :checked=>true) %><br>
  <%= f.label :wifi %>
  <%= f.radio_button(:adapter, "wifi") %><br>
  <%= f.submit "Continue", :class => "btn btn-default"%>
<% end %>
<% else %>
<p> It seems WiFi is unavailable for your device, meaning that you will be getting internet via LAN cable and share it via another LAN cable.
  Choose which adapter will you use to connect to internet:<br>
  <%= f.label :lan %>
  <%= f.radio_button(:adapter, "lan", :checked=>true) %><br>
  <%= f.submit "Continue", :class => "btn btn-default"%>
<% end %>
</div>

app/views/setup/quicksetup/quicksetup_2.html.erb
<div class = "container">
  
</div>

app/views/setup/quicksetup/quicksetup_3.html.erb
<div class = "container">
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class = "table table-bordered">
  <thead>
    <tr>
      <th>Username</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.level %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Level:</strong>
  <%= @user.level %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/wifi/status.html.erb
<div class = "container">
  <% if flash[:error] %>
  <div class = "alert alert-danger"><%= flash[:error] %></div>
  <% end %>
  <% if flash[:info] %>
  <div class = "alert alert-info"><%= flash[:info] %></div>
  <% end %>

  </div>
  <div class = "help_bar">
    Current version shows the version of the Debian-Router firmware
  </div>